name: Auto Merge Dependency Updates
on:
  - pull_request_target
jobs:
  auto-merge-dependency-updates:
    if: contains(github.event.pull_request.labels.*.name, 'automated')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: 'auto-merge:${{ github.head_ref }}'
      cancel-in-progress: true
    steps:
      - uses: Mic92/auto-merge@main
        with:
          use-auto-merge: true
          merge-method: merge
          required-labels: automated
